matrix:
  include:
    - los: osx
      anguage: objective-c
      osx_image: xcode7.3
    - os: osx
      language: objective-c
      osx_image: xcode8

script:
- set pipefail
- xcodebuild -project WebLinking.xcodeproj -scheme WebLinking test -sdk macosx | xcpretty
- xcodebuild -project WebLinking.xcodeproj -scheme WebLinking test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
